---
title: "iris_Apriori"
author: "Xie"
date: "2018/5/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 引用套件
```{r}
library(magrittr)

```

## 資料清理

```{r}
# 將iris資料引入data 變數
data <- iris

# 將iris資料轉換成factor型式
data$Species <- data$Species %>% as.factor()

# 觀察資料
summary(data)

# 將數值切成三個Range(小、中、大)，並回傳成Factor
Class<- function(Ary){
  DATA = c()
  Min = min(Ary)
  Max = max(Ary)
  Inter = (Max - Min)/3
  
  Output <- sapply(Ary,function(x){
    if(Min<= x && x < Min+Inter){
      DATA=c(DATA,"small")
    }else if(Min+Inter<= x && x < Min+Inter*2){
      DATA=c(DATA,"median")
    }else if(Min+Inter*2<= x && x <= Min+Inter*3){
      DATA=c(DATA,"large")
    }
  })
  return(Output)
}  


data$Sepal.Length <- Class(data$Sepal.Length) %>% as.factor()
data$Sepal.Width <- Class(data$Sepal.Width) %>% as.factor()
data$Petal.Length <- Class(data$Petal.Length) %>% as.factor()
data$Petal.Width <- Class(data$Petal.Width) %>% as.factor()
```

##　apriori　進行關聯性分析

```{r}
require(arules)
rule <- apriori(data, 
                parameter = list(minlen=4, supp=0.1, conf=0.7),
                appearance = list(default = "lhs",
                                  rhs = c("Species=setosa", "Species=versicolor", "Species=virginica")))

sort.rule <- sort(rule, by="lift")
inspect(sort.rule)
```

## apriori 視覺化

```{r}
require(arulesViz)
plot(sort.rule)
plot(sort.rule, method="graph", control=list(type="items"))
plot(sort.rule, method="grouped")
```

